develop:
  extends:
    file: base.yml
    service: base
  container_name: converter-develop
  environment:
    NODE_ENV: dev
    PORT: 4100
    API_GATEWAY_URL: http://192.168.99.100:8000
  command: develop
  volumes:
    - ./app:/opt/converter/app
