develop:
  extends:
    file: base.yml
    service: base
  container_name: converter-develop
  environment:
    NODE_ENV: dev
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4100
    PORT: 4100
  command: develop
  volumes:
    - ./app:/opt/converter/app
